# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
 platform :ios, '10.3'

target 'Phase0' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Phase0

  target 'Phase0-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Phase0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Phase0-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Phase0-tvOS

  target 'Phase0-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
